### ISSUE TITLE
Public derivation to calculate an equivalent R hash fails

### ISSUE THREAD

**Issue by ty-everett** [deanmlittle/rpuzzle#4]
```js
const rpuzzle = require('rpuzzle')
const bsv = require('bsv')
const hdKey = bsv.HDPrivateKey.fromRandom()
const kHex = hdKey.privateKey.toBuffer().toString('hex')
const puz1 = rpuzzle(rpuzzle.KValue.fromHex(kHex))
const puz2 = rpuzzle.fromPublicKey(hdKey.publicKey)
console.log(`${puz1.getRHash().toString('hex')} should equal ${puz2.getRHash().toString('hex')}`)
```

**Comment by deanmlittle** [comment]
Should be fixed in this commit. Good catch! https://github.com/deanmlittle/rpuzzle/commit/452cd8c5be9a2bef74ea227c1a5c3490c50c9777

**Comment by ty-everett** [comment]
Can we always do that with `.slice(1, 33)` though? There is some logic in the other functions for dealing with other edge cases:

```js
r0 = r[0] > 127 ? Buffer.concat([Buffer.alloc(1), r]) : r
```

**Comment by ty-everett** [comment]
Before your fix I made a workaround for my use-case that looks like this:

```js
const rpuzzle = require('rpuzzle')
const bsv = require('bsv')
const Point = require('bsv').crypto.Point
const hdKey = bsv.HDPrivateKey.fromRandom()
const kHex = hdKey.privateKey.toBuffer().toString('hex')
const puz1 = rpuzzle(rpuzzle.KValue.fromHex(kHex))
const r = hdKey.publicKey.point.x.umod(Point.getN()).toBuffer()
const r0 = r[0] > 127 ? Buffer.concat([Buffer.alloc(1), r]) : r
const puz2 = rpuzzle(rpuzzle.RValue(r0))
console.log(`${puz1.getRHash().toString('hex')} should equal ${puz2.getRHash().toString('hex')}`)
```

**Comment by deanmlittle** [comment]
Yes, it should be the case that we can. An R value is just the X coordinate of a public key. If it's compact, it'll be 02/03 at the front, then 32 X coordinate bytes . If it's expanded, it should be 04 followed by 32 X bytes, then 32 Y bytes. Regardless, slicing from 1-33 should always give us the X value. We then just need to add a 0 byte in front if the first byte >7f (127 in decimal). Writing some tests wouldn't be a bad idea. It's on the list for a reason 😉
